name: Deploy Static Site to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Sync HTML files (no-cache)
        run: |
          aws s3 sync . s3://www.moneymoose.co.in \
            --exclude "*" --include "*.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --delete

      - name: Sync all other files (long-cache)
        run: |
          aws s3 sync . s3://www.moneymoose.co.in \
            --exclude "*.html" \
            --delete
