name: Deploy Static Site to S3

on:
  push:
    branches: [learner]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync HTML files (no-cache)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude "*" --include "*.html" --cache-control "no-cache, no-store, must-revalidate"
        env:
          AWS_S3_BUCKET: www.moneymoose.co.in
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: .

      - name: Sync all other files (cacheable)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude "*.html"
        env:
          AWS_S3_BUCKET: www.moneymoose.co.in
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: .
